/* global window */
// LESGRIOTSxSTUDIO — projects data
// ⚠️  FICHIER GÉNÉRÉ AUTOMATIQUEMENT par backoffice/.
// Ne pas éditer à la main — ouvre le back office (http://localhost:3030).
// Dernière génération : 2026-05-24T16:24:03.657Z

const PROJECTS = [
  {
    id: "atavisme",
    name: "ATAVISM",
    role: "DIRECTION, DOP",
    client: "ARTE REPORTAGE",
    date: "09.2025",
    location: "DAKAR, SN",
    cover: "img/atavisme-01.jpg",
    strip: ["img/atavisme-01.jpg","img/atavisme-02.jpg"],
    resources: [
      { type: "image", src: "img/atavisme-01.jpg", label: "PORTRAIT, 01" },
      { type: "video", src: "img/atavisme-02.jpg", label: "FEATURE FILM — 12:20", aspect: "16 / 9", duration: 740 },
      { type: "image", src: "img/atavisme-02.jpg", label: "PORTRAIT, 02 — LEFT BANK" },
      { type: "image", src: "img/atavisme-01.jpg", label: "FILM PRINT" },
      { type: "image", src: "img/atavisme-02.jpg", label: "ATAVISM 03 — STAGE" },
      { type: "image", src: "img/atavisme-02.jpg", label: "ATAVISM 04 — POLAROID" },
      { type: "video", src: "img/atavisme-02.jpg", label: "ATAVISM REEL — 01:08", aspect: "16 / 9", duration: 68 },
      { type: "image", src: "img/atavisme-02.jpg", label: "ATAVISM CONTACT SHEET" },
      { type: "image", src: "img/atavisme-02.jpg", label: "ATAVISM BEHIND THE SCENES" },
      { type: "image", src: "img/atavisme-02.jpg", label: "ATAVISM STORYBOARD" },
      { type: "image", src: "img/atavisme-02.jpg", label: "ATAVISM 35MM, SCAN" },
      { type: "image", src: "img/atavisme-02.jpg", label: "ATAVISM TYPOGRAPHIC PLATE" },
      { type: "video", src: "img/atavisme-02.jpg", label: "ATAVISM TEASER ALT — 00:42", aspect: "16 / 9", duration: 42 },
    ],
    credits: {"DIRECTION":["AÏSSATOU DIOP"],"PRODUCTION":["LES GRIOTS","STUDIO BAMBOU"],"DOP":["MAWUNYO K."],"CAST":["IBRAHIMA SOW","FATIM N."],"POST":["PIA M. RENAUD"],"SOUND":["KOUYATÉ MANÉ"],"MUSIC":["MAALEM SAÏD"],"DISTRIBUTION":["ARTE REPORTAGE","JCC CARTHAGE"]},
    tags: ["FILM","DOCUMENTARY","12 MIN 20","SENEGAL","ANALOG","16MM","2025"],
  },
  {
    id: "mains",
    name: "HANDS, BOUND",
    role: "DIRECTION",
    client: "MAISON COUMBA",
    date: "03.2025",
    location: "PARIS, FR",
    cover: "img/mains-01.jpg",
    strip: ["img/mains-01.jpg","img/mains-01.jpg"],
    resources: [
      { type: "video", src: "img/mains-01.jpg", label: "FILM 06:14", aspect: "16 / 9", duration: 374 },
      { type: "image", src: "img/mains-01.jpg", label: "STILL, 01 — RED LAMP" },
      { type: "image", src: "img/mains-01.jpg", label: "STILL, 02 — WRISTS" },
      { type: "image", src: "img/mains-01.jpg", label: "HANDS 03 — STAGE" },
      { type: "image", src: "img/mains-01.jpg", label: "HANDS 04 — POLAROID" },
      { type: "video", src: "img/mains-01.jpg", label: "HANDS REEL — 01:08", aspect: "16 / 9", duration: 68 },
      { type: "image", src: "img/mains-01.jpg", label: "HANDS CONTACT SHEET" },
      { type: "image", src: "img/mains-01.jpg", label: "HANDS BEHIND THE SCENES" },
      { type: "image", src: "img/mains-01.jpg", label: "HANDS STORYBOARD" },
      { type: "image", src: "img/mains-01.jpg", label: "HANDS 35MM, SCAN" },
      { type: "image", src: "img/mains-01.jpg", label: "HANDS TYPOGRAPHIC PLATE" },
      { type: "video", src: "img/mains-01.jpg", label: "HANDS TEASER ALT — 00:42", aspect: "16 / 9", duration: 42 },
    ],
    credits: {"DIRECTION":["AÏSSATOU DIOP"],"PRODUCTION":["LES GRIOTS"],"DOP":["JULIETTE BARRA"],"CAST":["NDÈYE S.","OMAR L."],"STYLING":["ATELIER ZIGUINCHOR"],"JEWELRY":["MAISON COUMBA"],"POST":["PIA M. RENAUD"],"CLIENT":["MAISON COUMBA"]},
    tags: ["SHORT FILM","06 MIN 14","PARIS","MAISON COUMBA","2025"],
  },
  {
    id: "fila",
    name: "FILA × ABOU",
    role: "DIRECTION, STYLING",
    client: "FILA AFRICA",
    date: "04.2024",
    location: "DAKAR, SN",
    cover: "img/p-fila.jpg",
    strip: [],
    resources: [
      { type: "image", src: "img/p-fila.jpg", label: "DUO, COURT 01" },
      { type: "video", src: "img/p-fila.jpg", label: "LOOKBOOK FILM — 02:14", aspect: "16 / 9", duration: 134 },
      { type: "image", src: "img/p-fila.jpg", label: "LOOK 02, STRIPED SHIRT" },
      { type: "image", src: "img/p-fila.jpg", label: "FILA 03 — STAGE" },
      { type: "image", src: "img/p-fila.jpg", label: "FILA 04 — POLAROID" },
      { type: "video", src: "img/p-fila.jpg", label: "FILA REEL — 01:08", aspect: "16 / 9", duration: 68 },
      { type: "image", src: "img/p-fila.jpg", label: "FILA CONTACT SHEET" },
      { type: "image", src: "img/p-fila.jpg", label: "FILA BEHIND THE SCENES" },
      { type: "image", src: "img/p-fila.jpg", label: "FILA STORYBOARD" },
      { type: "image", src: "img/p-fila.jpg", label: "FILA 35MM, SCAN" },
      { type: "image", src: "img/p-fila.jpg", label: "FILA TYPOGRAPHIC PLATE" },
      { type: "video", src: "img/p-fila.jpg", label: "FILA TEASER ALT — 00:42", aspect: "16 / 9", duration: 42 },
    ],
    credits: {"DIRECTION":["AÏSSATOU DIOP"],"PHOTOGRAPHY":["MAWUNYO K."],"STYLING":["FATIM N."],"CAST":["ABOU SARR","MOUSTAPHA D."],"CLIENT":["FILA AFRICA"]},
    tags: ["CAMPAIGN","LOOKBOOK","FASHION","FILA","2024"],
  },
  {
    id: "yene",
    name: "YÉNÉ — MARABI",
    role: "DIRECTION",
    client: "MARABI RECORDS",
    date: "11.2024",
    location: "DAKAR, SN",
    cover: "img/atavisme-02.jpg",
    strip: ["img/atavisme-02.jpg","img/mains-01.jpg"],
    resources: [
      { type: "video", src: "img/atavisme-02.jpg", label: "MUSIC VIDEO — 03:24", aspect: "16 / 9", duration: 204 },
      { type: "image", src: "img/atavisme-02.jpg", label: "STILL 01 — BEACH" },
      { type: "image", src: "img/mains-01.jpg", label: "STILL 02 — INTERIOR" },
      { type: "image", src: "img/atavisme-02.jpg", label: "YÉNÉ 03 — STAGE" },
      { type: "image", src: "img/atavisme-02.jpg", label: "YÉNÉ 04 — POLAROID" },
      { type: "video", src: "img/atavisme-02.jpg", label: "YÉNÉ REEL — 01:08", aspect: "16 / 9", duration: 68 },
      { type: "image", src: "img/atavisme-02.jpg", label: "YÉNÉ CONTACT SHEET" },
      { type: "image", src: "img/atavisme-02.jpg", label: "YÉNÉ BEHIND THE SCENES" },
      { type: "image", src: "img/atavisme-02.jpg", label: "YÉNÉ STORYBOARD" },
      { type: "image", src: "img/atavisme-02.jpg", label: "YÉNÉ 35MM, SCAN" },
      { type: "image", src: "img/atavisme-02.jpg", label: "YÉNÉ TYPOGRAPHIC PLATE" },
      { type: "video", src: "img/atavisme-02.jpg", label: "YÉNÉ TEASER ALT — 00:42", aspect: "16 / 9", duration: 42 },
    ],
    credits: {"DIRECTION":["AÏSSATOU DIOP"],"PRODUCTION":["LES GRIOTS"],"ARTIST":["YÉNÉ"],"DOP":["MAWUNYO K."],"LABEL":["MARABI RECORDS"]},
    tags: ["MUSIC VIDEO","03 MIN 24","YÉNÉ","MARABI","2024"],
  },
  {
    id: "indigo-cristal",
    name: "INDIGO CRISTAL",
    role: "DIRECTION",
    client: "SWEET NOIR CAPUCHE",
    date: "—",
    location: "—",
    cover: "img/indigo-cristal-cover.jpg",
    thumbVideo: "img/indigo-cristal-thumb.mp4",
    strip: ["img/indigo-cristal-cover.jpg"],
    resources: [
      { type: "video", src: "img/indigo-cristal.mp4", label: "INDIGO CRISTAL — XML V3 / TIMON · 02:19", aspect: "16 / 9", duration: 139 },
      { type: "image", src: "img/atavisme-01.jpg", label: "INDIGO CRISTAL — VISUEL 01" },
    ],
    credits: {"DIRECTION":["—"],"CLIENT":["SWEET NOIR CAPUCHE"]},
    tags: ["CAMPAIGN"],
  },
  {
    id: "survival-tour-riles",
    name: "SURVIVAL TOUR",
    role: "MOVEMENT DIRECTION",
    client: "RILES",
    date: "2025—2026",
    location: "—",
    cover: "img/p-fila.jpg",
    strip: ["img/p-fila.jpg"],
    resources: [
      { type: "image", src: "img/p-fila.jpg", label: "SURVIVAL TOUR — STAGE 01" },
    ],
    credits: {"MOVEMENT DIRECTION":["—"],"ARTIST":["RILES"]},
    tags: ["STAGE","MUSIC"],
  },
  {
    id: "vacra-galatee",
    name: "GALATÉE",
    role: "CREATIVE DIRECTION",
    client: "VACRA",
    date: "2023",
    location: "—",
    cover: "img/florale-01.jpg",
    strip: ["img/florale-01.jpg"],
    resources: [
      { type: "image", src: "img/florale-01.jpg", label: "GALATÉE — VISUEL 01" },
    ],
    credits: {"CREATIVE DIRECTION":["—"],"ARTIST":["VACRA"]},
    tags: ["MUSIC VIDEO","CREATIVE DIRECTION"],
  },
  {
    id: "anais-cardot-fomo",
    name: "FOMO",
    role: "MOVEMENT DIRECTION",
    client: "ANAÏS CARDOT",
    date: "—",
    location: "—",
    cover: "img/mains-01.jpg",
    strip: ["img/mains-01.jpg"],
    resources: [
      { type: "image", src: "img/mains-01.jpg", label: "FOMO — VISUEL 01" },
    ],
    credits: {"MOVEMENT DIRECTION":["—"],"ARTIST":["ANAÏS CARDOT"]},
    tags: ["MUSIC VIDEO","MOVEMENT"],
  },
  {
    id: "ava-x-nike-courir",
    name: "AVA X NIKE × COURIR",
    role: "MOVEMENT DIRECTION",
    client: "",
    date: "—",
    location: "—",
    cover: "img/nike-1.jpg",
    thumbVideo: "img/nike-thumb.mp4",
    strip: ["img/nike-1.jpg","img/nike-2.jpg","img/nike-3.jpg","img/nike-4.jpg"],
    resources: [
      { type: "video", src: "img/nike/Courir_AvaX_1_16-9.mov", poster: "img/nike-1.jpg", label: "AVA X · NIKE × COURIR — FILM 01", aspect: "16/9" },
      { type: "video", src: "img/nike/Courir_AvaX_2_16-9.mov", poster: "img/nike-2.jpg", label: "AVA X · NIKE × COURIR — FILM 02", aspect: "16/9" },
      { type: "video", src: "img/nike/Courir_AvaX_3_16-9.mov", poster: "img/nike-3.jpg", label: "AVA X · NIKE × COURIR — FILM 03", aspect: "16/9" },
      { type: "video", src: "img/nike/Courir_AvaX_4_16-9.mov", poster: "img/nike-4.jpg", label: "AVA X · NIKE × COURIR — FILM 04", aspect: "16/9" },
    ],
    credits: {"MOVEMENT DIRECTION":["—"],"ARTIST":["AVA X"],"BRAND":["NIKE","COURIR"],"AGENCY":["IMAGINE NATION"]},
    tags: ["CAMPAIGN","BRAND","MOVEMENT"],
  },
  {
    id: "tiers-monde-les-oublies",
    name: "LES OUBLIÉS",
    role: "PRODUCTION",
    client: "TIERS MONDE",
    date: "—",
    location: "—",
    cover: "img/atavisme-02.jpg",
    strip: ["img/atavisme-02.jpg"],
    resources: [
      { type: "image", src: "img/atavisme-02.jpg", label: "LES OUBLIÉS — VISUEL 01" },
    ],
    credits: {"PRODUCTION":["—"],"ARTIST":["TIERS MONDE"]},
    tags: ["MUSIC VIDEO","PRODUCTION"],
  },
  {
    id: "yasuke",
    name: "EESAH YASUKE",
    role: "CREATIVE DIRECTION",
    date: "2026",
    location: "—",
    cover: "data:image/svg+xml;utf8,%3Csvg%20xmlns%3D%22http%3A%2F%2Fwww.w3.org%2F2000%2Fsvg%22%20viewBox%3D%220%200%20800%20600%22%20preserveAspectRatio%3D%22xMidYMid%20slice%22%3E%3Crect%20width%3D%22800%22%20height%3D%22600%22%20fill%3D%22%230a0a0a%22%2F%3E%3Ctext%20x%3D%22400%22%20y%3D%22305%22%20font-family%3D%22Geist%20Mono%2C%20monospace%22%20font-size%3D%2236%22%20font-weight%3D%22500%22%20fill%3D%22%23f6e21c%22%20text-anchor%3D%22middle%22%20dominant-baseline%3D%22middle%22%20letter-spacing%3D%222%22%3EEESAH%20YASUKE%3C%2Ftext%3E%3Ctext%20x%3D%22400%22%20y%3D%22350%22%20font-family%3D%22Geist%20Mono%2C%20monospace%22%20font-size%3D%2211%22%20fill%3D%22%238a8378%22%20text-anchor%3D%22middle%22%20letter-spacing%3D%223%22%3ENO%20COVER%20YET%3C%2Ftext%3E%3C%2Fsvg%3E",
    strip: [],
    resources: [],
    credits: {},
    tags: [],
  },
];

const SITE_CONTENT = {
  "aboutIntro": {
    "en": [
      "LESGRIOTSxSTUDIO IS A TRANSDISCIPLINARY CREATIVE STUDIO.",
      "WE COMBINE ARTISTIC DIRECTION, MOVEMENT, AND AUDIOVISUAL PRODUCTION TO DESIGN NARRATIVES THAT RESONATE ACROSS IMAGE, STORY, AND PERFORMANCE.",
      "OUR PRACTICE IS ROOTED IN AFRO-DIASPORIC PERSPECTIVES AND DEDICATED TO BUILDING CULTURAL LEGACIES THROUGH POWERFUL VISUAL STORYTELLING.",
      "WE ARE DRIVEN BY COLLABORATION AND THRIVE IN CREATIVE ENVIRONMENTS WHERE MEANING AND IMPACT ARE AT THE CORE."
    ],
    "fr": [
      "LESGRIOTSxSTUDIO EST UN STUDIO CRÉATIF TRANSDISCIPLINAIRE.",
      "NOUS RÉUNISSONS DIRECTION ARTISTIQUE, MOUVEMENT ET PRODUCTION AUDIOVISUELLE POUR CONSTRUIRE DES RÉCITS QUI RÉSONNENT À TRAVERS L'IMAGE, L'HISTOIRE ET LA PERFORMANCE.",
      "NOTRE PRATIQUE EST ANCRÉE DANS DES PERSPECTIVES AFRO-DIASPORIQUES ET DÉDIÉE À LA CONSTRUCTION D'HÉRITAGES CULTURELS PAR UN STORYTELLING VISUEL PUISSANT.",
      "NOUS SOMMES MUS PAR LA COLLABORATION ET PROSPÉRONS DANS DES ENVIRONNEMENTS CRÉATIFS OÙ LE SENS ET L'IMPACT SONT AU CŒUR."
    ]
  },
  "activePages": {
    "work": true,
    "about": true,
    "eco": true
  }
};

if (typeof window !== "undefined") {
  window.PROJECTS = PROJECTS;
  window.SITE_CONTENT = SITE_CONTENT;
}
