// Champs du formulaire Ressource — partagés entre /resources/new et /resources/[id].
// Inspiré des pages produit The Futur : couverture, accroche, description,
// "ce que tu obtiens", auteur — puis le fichier et la dispo.
export const RESOURCE_FIELDS = [
  { key: "title", label: "Titre", type: "text", required: true },
  { key: "subtitle", label: "Accroche (sous-titre)", type: "text",
    hint: "Une phrase qui donne envie. Ex : « Le template qui structure ton offre en 1 page. »" },
  { key: "type", label: "Type", type: "select",
    options: ["guide", "article", "template", "outil"] },
  { key: "format", label: "Format", type: "text",
    hint: 'ex: "PDF · 12 PAGES" ou "LECTURE · 6 MIN"' },
  { key: "author", label: "Auteur", type: "text",
    hint: "ex : Moos Coulibaly — affiché en crédit sur la page" },
  { key: "cover", label: "Image de couverture", type: "file",
    subdir: "ressources",
    accept: ".jpg,.jpeg,.png,.svg,.webp",
    placeholder: "img/ressources/cover.jpg ou https://...",
    hint: "Visuel en haut de la page ressource (aperçu du PDF/template). Optionnel mais recommandé." },
  { key: "description", label: "Description", type: "textarea", rows: 5,
    hint: "Explique ce qu'est la ressource, à qui elle sert, ce qu'elle résout. Une ligne vide = nouveau paragraphe." },
  { key: "whatsInside", label: "Ce que tu obtiens", type: "textarea", rows: 6,
    hint: "Un point par ligne — la liste à puces affichée sur la page (chapitres, outils, sections inclus)." },
  { key: "href", label: "Fichier ou URL à télécharger", type: "file",
    subdir: "ressources",
    accept: ".pdf,.jpg,.jpeg,.png,.svg,.webp,.zip,.fig",
    placeholder: "img/ressources/guide.pdf ou https://...",
    hint: 'Uploade un PDF/template (rangé dans apps/lagriotheque/img/ressources/) OU colle une URL externe. Laisse vide pour "bientôt".' },
  { key: "available", label: "Disponible maintenant ?", type: "bool" },
];
